"""Compute KPIs from the SQLite warehouse and write reports/kpi_summary.md.

Parses the named queries in sql/kpi_queries.sql (each preceded by a
`-- name: <section>` comment), executes them against data/supply_chain.db,
and renders every result as a Markdown table. All numbers in the report are
computed from the data — nothing is hand-written.

Usage:
    python src/compute_kpis.py
"""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
SQL_FILE = BASE / "sql" / "kpi_queries.sql"
DB = BASE / "data" / "supply_chain.db"
OUT = BASE / "reports" / "kpi_summary.md"

TITLES = {
    "headline": "1. Headline delivery KPIs",
    "carrier_scorecard": "2. Carrier scorecard (late rate, cost, pickup SLA)",
    "warehouse_scorecard": "3. Warehouse throughput and reliability",
    "province_performance": "4. Provincial delivery performance",
    "ship_mode": "5. Shipping cost and reliability by ship mode",
    "monthly_trend": "6. Monthly trend (24 months)",
    "winter_effect": "7. Winter vs rest of year",
    "accuracy_breakdown": "8. Order accuracy breakdown",
    "disruption": "9. March 2025 disruption vs baseline",
    "category_performance": "10. Late rate by product category",
}


def parse_queries(text: str) -> list[tuple[str, str]]:
    """Split the SQL file into (name, sql) using `-- name:` markers."""
    parts = re.split(r"--\s*name:\s*(\w+)", text)
    # parts[0] is the header comment; then alternating name, sql, name, sql...
    queries = []
    for i in range(1, len(parts) - 1, 2):
        queries.append((parts[i].strip(), parts[i + 1].strip().rstrip(";")))
    return queries


def md_table(columns: list[str], rows: list[tuple]) -> str:
    def fmt(v):
        if v is None:
            return "—"
        if isinstance(v, float):
            return f"{v:,.2f}"
        if isinstance(v, int):
            return f"{v:,}"
        return str(v)

    head = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join("---" for _ in columns) + " |"
    body = "\n".join("| " + " | ".join(fmt(v) for v in r) + " |" for r in rows)
    return head + "\n" + sep + "\n" + body


def main() -> Path:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    queries = parse_queries(SQL_FILE.read_text())
    con = sqlite3.connect(DB)

    lines = [
        "# Supply Chain KPI Summary",
        "",
        "_All figures computed from `data/supply_chain.db` (synthetic data, "
        "seed 42). Generated by `src/compute_kpis.py` — do not edit by hand._",
        "",
    ]
    for name, sql in queries:
        cur = con.execute(sql)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
        lines.append(f"## {TITLES.get(name, name)}")
        lines.append("")
        lines.append(md_table(cols, rows))
        lines.append("")
    con.close()
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(queries)} KPI sections)")
    return OUT


if __name__ == "__main__":
    main()
